/* js/materials.js – shared phonics data used by activity pages */
'use strict';

const PHONICS_DATA = {
  alphabet: [
    { l: 'A', word: 'Apple',    emoji: '🍎', sound: 'aah',  vowel: true },
    { l: 'B', word: 'Ball',     emoji: '⚽', phoneme: '/b/', ttsHint: 'voiced stop', vowel: false },
    { l: 'C', word: 'Cat',      emoji: '🐱', phoneme: '/k/', ttsHint: 'voiceless stop', vowel: false },
    { l: 'D', word: 'Dog',      emoji: '🐶', phoneme: '/d/', ttsHint: 'voiced stop', vowel: false },
    { l: 'E', word: 'Elephant', emoji: '🐘', sound: 'eh',   vowel: true },
    { l: 'F', word: 'Fish',     emoji: '🐟', phoneme: '/f/', ttsHint: 'voiceless fricative', vowel: false },
    { l: 'G', word: 'Gorilla',  emoji: '🦍', phoneme: '/g/', ttsHint: 'voiced stop', vowel: false },
    { l: 'H', word: 'Hat',      emoji: '🎩', phoneme: '/h/', ttsHint: 'voiceless fricative', vowel: false },
    { l: 'I', word: 'Igloo',    emoji: '🏔️', sound: 'ih',   vowel: true },
    { l: 'J', word: 'Jet',      emoji: '✈️', phoneme: '/j/', ttsHint: 'voiced affricate-ish', vowel: false },
    { l: 'K', word: 'Kite',     emoji: '🪁', phoneme: '/k/', ttsHint: 'voiceless stop', vowel: false },
    { l: 'L', word: 'Lion',     emoji: '🦁', phoneme: '/l/', ttsHint: 'alveolar lateral', vowel: false },
    { l: 'M', word: 'Moon',     emoji: '🌙', phoneme: '/m/', ttsHint: 'bilabial nasal', vowel: false },
    { l: 'N', word: 'Net',      emoji: '🥅', phoneme: '/n/', ttsHint: 'alveolar nasal', vowel: false },
    { l: 'O', word: 'Orange',   emoji: '🍊', sound: 'oh',   vowel: true },
    { l: 'P', word: 'Pig',      emoji: '🐷', phoneme: '/p/', ttsHint: 'voiceless stop', vowel: false },
    { l: 'Q', word: 'Queen',    emoji: '👑', phoneme: '/kw/', ttsHint: 'kw cluster', vowel: false },
    { l: 'R', word: 'Rabbit',   emoji: '🐰', phoneme: '/r/', ttsHint: 'alveolar approximant', vowel: false },
    { l: 'S', word: 'Sun',      emoji: '☀️', phoneme: '/s/', ttsHint: 'voiceless fricative', vowel: false },
    { l: 'T', word: 'Tiger',    emoji: '🐯', phoneme: '/t/', ttsHint: 'voiceless stop', vowel: false },
    { l: 'U', word: 'Umbrella', emoji: '☂️', sound: 'uh',   vowel: true },
    { l: 'V', word: 'Van',      emoji: '🚐', phoneme: '/v/', ttsHint: 'voiced fricative', vowel: false },
    { l: 'W', word: 'Whale',    emoji: '🐋', phoneme: '/w/', ttsHint: 'glide', vowel: false },
    { l: 'X', word: 'X-ray',    emoji: '🩻', phoneme: '/ks/', ttsHint: 'cluster ks', vowel: false },
    { l: 'Y', word: 'Yak',      emoji: '🐃', phoneme: '/j/', ttsHint: 'y glide', vowel: false },
    { l: 'Z', word: 'Zebra',    emoji: '🦓', phoneme: '/z/', ttsHint: 'voiced fricative', vowel: false },
  ],

  digraphs: [
    { pair:'SH', word:'Shark',   emoji:'🦈', example:'sh-ark', sound:'shh'  },
    { pair:'CH', word:'Cheese',  emoji:'🧀', example:'ch-eese',sound:'ch'   },
    { pair:'TH', word:'Thumb',   emoji:'👍', example:'th-umb', sound:'th'   },
    { pair:'WH', word:'Whale',   emoji:'🐳', example:'wh-ale', sound:'wh'   },
    { pair:'PH', word:'Phone',   emoji:'📱', example:'ph-one', sound:'fuh'  },
    { pair:'CK', word:'Clock',   emoji:'🕐', example:'cl-ock', sound:'kuh'  },
    { pair:'NG', word:'Ring',    emoji:'💍', example:'ri-ng',  sound:'ng'   },
    { pair:'QU', word:'Queen',   emoji:'👑', example:'qu-een', sound:'kwuh' },
  ],

  cvc: [
    { word:'cat', emoji:'🐱' }, { word:'dog', emoji:'🐶' }, { word:'hat', emoji:'🎩' },
    { word:'bug', emoji:'🐛' }, { word:'sun', emoji:'☀️' }, { word:'cup', emoji:'☕' },
    { word:'pen', emoji:'🖊️' }, { word:'pin', emoji:'📌' }, { word:'hop', emoji:'🐸' },
    { word:'bit', emoji:'🦷' }, { word:'red', emoji:'🔴' }, { word:'wet', emoji:'💧' },
    { word:'lip', emoji:'💋' }, { word:'log', emoji:'🪵' }, { word:'mud', emoji:'🟤' },
    { word:'nut', emoji:'🌰' }, { word:'rob', emoji:'👨' }, { word:'tip', emoji:'💡' },
  ],

  sightWords: [
    'the','and','a','to','is','in','it','you','of','that',
    'he','was','for','on','are','as','with','his','they','at',
    'be','this','from','or','one','had','by','but','not','what',
    'all','were','we','when','your','can','said','there','use','an',
    'each','which','she','do','how','their','if','will','up','other',
    'about','out','many','then','them','these','so','some','her','would',
  ],

  vowels: [
    { letter:'A', short:{ word:'apple',  emoji:'🍎', sound:'aah' }, long:{ word:'ape',   emoji:'🦍', sound:'ay'  } },
    { letter:'E', short:{ word:'egg',    emoji:'🥚', sound:'eh'  }, long:{ word:'eel',   emoji:'🐍', sound:'ee'  } },
    { letter:'I', short:{ word:'igloo',  emoji:'🏔️', sound:'ih'  }, long:{ word:'ice',   emoji:'🧊', sound:'eye' } },
    { letter:'O', short:{ word:'octopus',emoji:'🐙', sound:'oh'  }, long:{ word:'oak',   emoji:'🌳', sound:'oh'  } },
    { letter:'U', short:{ word:'umbrella',emoji:'☂️',sound:'uh'  }, long:{ word:'unicorn',emoji:'🦄',sound:'you' } },
  ],

  consonantBlends: [
    { blend:'bl', word:'blue',  emoji:'🔵' }, { blend:'br', word:'bread',  emoji:'🍞' },
    { blend:'cl', word:'cloud', emoji:'☁️' }, { blend:'cr', word:'crown',  emoji:'👑' },
    { blend:'dr', word:'drum',  emoji:'🥁' }, { blend:'fl', word:'flag',   emoji:'🚩' },
    { blend:'fr', word:'frog',  emoji:'🐸' }, { blend:'gl', word:'globe',  emoji:'🌎' },
    { blend:'gr', word:'grapes',emoji:'🍇' }, { blend:'pl', word:'plane',  emoji:'✈️' },
    { blend:'pr', word:'prince',emoji:'🤴' }, { blend:'sc', word:'scarf',  emoji:'🧣' },
    { blend:'sk', word:'skip',  emoji:'⏩' }, { blend:'sl', word:'sled',   emoji:'🛷' },
    { blend:'sm', word:'smile', emoji:'😊' }, { blend:'sn', word:'snail',  emoji:'🐌' },
    { blend:'sp', word:'spoon', emoji:'🥄' }, { blend:'st', word:'star',   emoji:'⭐' },
    { blend:'sw', word:'swan',  emoji:'🦢' }, { blend:'tr', word:'train',  emoji:'🚂' },
    { blend:'tw', word:'twins', emoji:'👥' }, { blend:'wr', word:'wrist',  emoji:'🤚' },
  ],

  magicE: [
    { cvc:'cap', magic:'cape', emoji1:'🧢', emoji2:'🦸' },
    { cvc:'kit', magic:'kite', emoji1:'🧰', emoji2:'🪁' },
    { cvc:'hop', magic:'hope', emoji1:'🐸', emoji2:'🤞' },
    { cvc:'cub', magic:'cube', emoji1:'🐻', emoji2:'🎲' },
    { cvc:'pin', magic:'pine', emoji1:'📌', emoji2:'🌲' },
    { cvc:'man', magic:'mane', emoji1:'👨', emoji2:'🦁' },
    { cvc:'rid', magic:'ride', emoji1:'😤', emoji2:'🚲' },
    { cvc:'fad', magic:'fade', emoji1:'😐', emoji2:'🌅' },
  ],

  rhymes: [
    { family:'at', words:['cat','bat','hat','mat','rat','sat','fat','pat'] },
    { family:'an', words:['can','fan','man','pan','ran','tan','van','ban'] },
    { family:'in', words:['bin','fin','pin','sin','tin','win','kin','gin'] },
    { family:'og', words:['bog','dog','fog','hog','log','cog','tog','frog'] },
    { family:'un', words:['bun','fun','gun','nun','pun','run','sun','nun'] },
    { family:'ip', words:['dip','hip','lip','nip','rip','sip','tip','zip'] },
  ],

  diphthongs: [
    { letters:'oi', word:'coin',     emoji:'🪙', sounds:'oy' },
    { letters:'oi', word:'boil',     emoji:'💧', sounds:'oy' },
    { letters:'oi', word:'foil',     emoji:'🌿', sounds:'oy' },
    { letters:'oy', word:'toy',      emoji:'🧸', sounds:'oy' },
    { letters:'oy', word:'boy',      emoji:'👦', sounds:'oy' },
    { letters:'oy', word:'joy',      emoji:'😊', sounds:'oy' },
    { letters:'ou', word:'house',    emoji:'🏠', sounds:'ow' },
    { letters:'ou', word:'mouse',    emoji:'🐭', sounds:'ow' },
    { letters:'ou', word:'cloud',    emoji:'☁️', sounds:'ow' },
    { letters:'ow', word:'cow',      emoji:'🐄', sounds:'ow' },
    { letters:'ow', word:'owl',      emoji:'🦉', sounds:'ow' },
    { letters:'ow', word:'bow',      emoji:'🏹', sounds:'ow' },
  ],

  vowelVariants: [
    { letters:'ea', word:'bread',    emoji:'🍞', sound1:'eh', sound2:'ay', primary:'eh' },
    { letters:'ea', word:'leaf',     emoji:'🍃', sound1:'eh', sound2:'ay', primary:'ay' },
    { letters:'ea', word:'head',     emoji:'🦴', sound1:'eh', sound2:'ay', primary:'eh' },
    { letters:'ea', word:'read',     emoji:'📖', sound1:'eh', sound2:'ay', primary:'ay' },
    { letters:'oo', word:'book',     emoji:'📕', sound1:'uh', sound2:'oo', primary:'uh' },
    { letters:'oo', word:'moon',     emoji:'🌙', sound1:'uh', sound2:'oo', primary:'oo' },
    { letters:'oo', word:'foot',     emoji:'🦶', sound1:'uh', sound2:'oo', primary:'uh' },
    { letters:'oo', word:'food',     emoji:'🍕', sound1:'uh', sound2:'oo', primary:'oo' },
  ],

  syllables: [
    { word:'cat',      type:'closed',    syllables:1, emoji:'🐱', breakdown:'cat' },
    { word:'go',       type:'open',      syllables:1, emoji:'🚀', breakdown:'go' },
    { word:'cake',     type:'silent-e',  syllables:1, emoji:'🎂', breakdown:'cake' },
    { word:'team',     type:'vowel-team',syllables:1, emoji:'⚽', breakdown:'team' },
    { word:'napkin',   type:'closed',    syllables:2, emoji:'🧻', breakdown:'nap·kin' },
    { word:'paper',    type:'open',      syllables:2, emoji:'📄', breakdown:'pa·per' },
    { word:'gentle',   type:'silent-e',  syllables:2, emoji:'💚', breakdown:'gen·tle' },
    { word:'ocean',    type:'vowel-team',syllables:2, emoji:'🌊', breakdown:'o·cean' },
    { word:'rabbit',   type:'closed',    syllables:2, emoji:'🐰', breakdown:'rab·bit' },
    { word:'table',    type:'open',      syllables:2, emoji:'🪑', breakdown:'ta·ble' },
  ],

  vowelDigraphs: [
    { pair:'ea', word:'bread',   emoji:'🍞', sound:'short-eh', sounds:['short-eh','long-ay'] },
    { pair:'ea', word:'leaf',    emoji:'🍃', sound:'long-ay', sounds:['short-eh','long-ay'] },
    { pair:'ea', word:'head',    emoji:'🦴', sound:'short-eh', sounds:['short-eh','long-ay'] },
    { pair:'ea', word:'read',    emoji:'📖', sound:'long-ay', sounds:['short-eh','long-ay'] },
    { pair:'oo', word:'book',    emoji:'📕', sound:'short-oo', sounds:['short-oo','long-oo'] },
    { pair:'oo', word:'moon',    emoji:'🌙', sound:'long-oo', sounds:['short-oo','long-oo'] },
    { pair:'oo', word:'foot',    emoji:'🦶', sound:'short-oo', sounds:['short-oo','long-oo'] },
    { pair:'oo', word:'food',    emoji:'🍕', sound:'long-oo', sounds:['short-oo','long-oo'] },
    { pair:'ai', word:'rain',    emoji:'🌧️', sound:'long-ay', sounds:['long-ay'] },
    { pair:'ay', word:'play',    emoji:'🎮', sound:'long-ay', sounds:['long-ay'] },
    { pair:'ee', word:'bee',     emoji:'🐝', sound:'long-ee', sounds:['long-ee'] },
    { pair:'ie', word:'pie',     emoji:'🥧', sound:'long-eye', sounds:['long-eye'] },
    { pair:'oa', word:'boat',    emoji:'⛵', sound:'long-oh', sounds:['long-oh'] },
    { pair:'ue', word:'blue',    emoji:'🔵', sound:'long-oo', sounds:['long-oo'] },
    { pair:'igh', word:'light',  emoji:'💡', sound:'long-eye', sounds:['long-eye'] },
  ],
};
